baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Voxe51 Doc'
[module]
  [[module.imports]]
    path = 'github.com/thingsym/hugo-theme-techdoc'
#theme = 'hugo-theme-relearn'
[params]
linkTitle = 'Voxel51'

